CREATE TABLE IF NOT EXISTS "beers" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" varchar(100) NOT NULL,
	"type" varchar(50) NOT NULL,
	"malt" text,
	"hop" text,
	"water" text,
	"yeast" varchar(100),
	"additives" text,
	"volume" numeric(5, 1) NOT NULL,
	"og" numeric(4, 3),
	"fg" numeric(4, 3),
	"memo" text,
	"fermentation_start" date NOT NULL,
	"fermentation_end" date NOT NULL,
	"fermentation_temp" numeric(3, 1) NOT NULL,
	"fermentation_actual_temp" numeric(3, 1),
	"fermentation_actual_humidity" numeric(3, 1),
	"aging_start" date NOT NULL,
	"aging_end" date NOT NULL,
	"aging_temp" numeric(3, 1) NOT NULL,
	"aging_actual_temp" numeric(3, 1),
	"aging_actual_humidity" numeric(3, 1),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
