import type { Metadata } from 'next';
import { IBM_Plex_Sans, IBM_Plex_Sans_Thai_Looped } from 'next/font/google';
import './globals.css';

const ibmPlexSans = IBM_Plex_Sans({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="dark">
			<body className={`${ibmPlexSans.variable} antialiased`}>{children}</body>
		</html>
	);
}
